# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Glasskube < Formula
  desc "Glasskube is a cloud native package manager for Kubernetes. It includes an UI and CLI, is dependency aware and GitOps ready."
  homepage "https://glasskube.dev"
  version "0.6.0"
  license "Apache-2.0"

  on_macos do
    on_intel do
      url "https://releases.dl.glasskube.dev/glasskube_v0.6.0_darwin_x86_64.tar.gz"
      sha256 "72ea3aaefb0699f1a7704c309a899aace30b6ec360c19aca7fe371383c6fd13d"

      def install
        bin.install "glasskube"
      end
    end
    on_arm do
      url "https://releases.dl.glasskube.dev/glasskube_v0.6.0_darwin_arm64.tar.gz"
      sha256 "a6c617a19b4d488488a8a7795125564d595e871bc77214a757107cb7d95f3d93"

      def install
        bin.install "glasskube"
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://releases.dl.glasskube.dev/glasskube_v0.6.0_linux_x86_64.tar.gz"
        sha256 "7863188ec2375b94523ac52788bb3b68830dc998794cb305557c07e5618de7e9"

        def install
          bin.install "glasskube"
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://releases.dl.glasskube.dev/glasskube_v0.6.0_linux_arm64.tar.gz"
        sha256 "4e4fb7c423503dd90a503b0ee094f24588ea9dd464d8d0cdccafc850ca2ffb14"

        def install
          bin.install "glasskube"
        end
      end
    end
  end
end
